import sympy as sp


def function_graph_config(expr, x_min: float = -10, x_max: float = 10) -> dict:
    expression = sp.sstr(expr)
    latex = sp.latex(expr)
    return {
        "type": "graph2d",
        "expression": expression,
        "latex": latex,
        "functions": [
            {
                "id": "f1",
                "kind": "expression",
                "expression": expression,
                "latex": latex,
                "label": "f",
                "color": "#0f766e",
                "strokeWidth": 3,
                "domainMode": "auto",
                "domainMin": None,
                "domainMax": None,
                "functionExtensionMode": "auto",
                "functionExtension": 0.25,
                "functionExtensionLeft": 0.25,
                "functionExtensionRight": 0.25,
                "pieces": [],
            }
        ],
        "xMin": x_min,
        "xMax": x_max,
        "yMin": -10,
        "yMax": 10,
        "widthPx": 680,
        "heightPx": 300,
        "equalScale": False,
        "showGrid": True,
        "showMajorGrid": True,
        "showMinorGrid": False,
        "showGridBorder": False,
        "showAxes": True,
        "showArrows": True,
        "showAxisLabels": True,
        "axisLabelIntervalMode": "auto",
        "axisLabelStepX": None,
        "axisLabelStepY": None,
        "axisLabelMinSpacingPx": 48,
        "showFunctionArrows": True,
        "gridMajorStep": 1,
        "gridMinorStep": 0.5,
        "gridMajorStepX": 1,
        "gridMajorStepY": 1,
        "gridMinorStepX": 0.5,
        "gridMinorStepY": 0.5,
        "gridMajorColor": "#b9b9b9",
        "gridMinorColor": "#dddddd",
        "axisExtensionMode": "auto",
        "functionExtensionMode": "auto",
        "axisExtension": 0.5,
        "functionExtension": 0.25,
        "functionExtensionLeft": 0.25,
        "functionExtensionRight": 0.25,
        "metadata": {},
    }
